services:
  - type: web
    name: mesa-exchange-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: ROBLOX_CLIENT_ID
        sync: false
      - key: ROBLOX_CLIENT_SECRET
        sync: false